/*
 * ctrl_marche.c
 *
 * Created: 15/11/2011 17:08:52
 *  Author: berryer
 */ 

#include "ctrl_marche.h"
#include "ctrl_patte.h"


#define TIMEOUT_MIN_SPEED	4 //(400ms)



static Int8U timeout = 0;
static Int8U step = 0;

#define AMPLITUDE_MAX_EPAULE					25
#define AMPLITUDE_MAX_COUDE						20


/////////////////////////////////////////PRIVATE FUNCTIONS/////////////////////////////////////////
static void CtrlMarcheSequence( void ) ;
static void CtrlMarcheSequenceStop( void ) ;
static void CtrlMarcheSequenceForward( void ) ;
static void CtrlMarcheSequenceBackward( void ) ;
static void CtrlMarcheSequenceLeft( void ) ;
static void CtrlMarcheSequenceRight( void ) ;
static void CtrlMarcheSequenceLeftSide( void ) ;
static void CtrlMarcheSequenceRightSide( void ) ;


static move_t mouvement;
/////////////////////////////////////////PUBLIC FUNCTIONS/////////////////////////////////////////
//init
void CtrlMarche( void ) 
{
	mouvement.move = E_MOVE_STOP;
	mouvement.speed = E_SPEED_0;
	
	CtrlPatte();
	CtrlMarcheSequenceStop();
}

//dispatcher
void CtrlMarcheDispatcher( Event_t event )  
{
	if ( DrvEventTestEvent(event, CONF_EVENT_TIMER_100MS ))
	{
		if( mouvement.move != E_MOVE_STOP)
		{
			if ( timeout >= TIMEOUT_MIN_SPEED + mouvement.speed)
			{
				CtrlMarcheSequence();
				timeout = 0;
			}
			else
			{
				timeout++;
			}	
		}
	}
}

//on recupere la structure
move_t* CtrlMarcheGetStruct( void )
{
	return &mouvement;	
}


void CtrlMarcheMove( EMove move, ESpeed speed ) 
{
	mouvement.move = move;
	mouvement.speed = speed;
}



/////////////////////////////////////////PRIVATE FUNCTIONS/////////////////////////////////////////
static void CtrlMarcheSequence( void )
{
	//coude gauche vers l'exterieur positif
	//coude droit vers l'exterieur negatif
	//epaule gauche vers l'arriere negatif
	//epaule droite vers l'arriere positif
	
	if( mouvement.move == E_MOVE_STOP )
	{
		CtrlMarcheSequenceStop();
		step = 0;
	}	
	else if( mouvement.move == E_MOVE_FORWORD )
	{
		CtrlMarcheSequenceForward();
	}
	else if( mouvement.move == E_MOVE_BACKWORD )
	{
		CtrlMarcheSequenceBackward();
	}
	else if( mouvement.move == E_MOVE_LEFT )
	{
		CtrlMarcheSequenceLeft();
	}	
	else if( mouvement.move == E_MOVE_RIGHT )
	{
		CtrlMarcheSequenceRight();
	}	
	else if( mouvement.move == E_MOVE_LEFT_SIDE )
	{
		CtrlMarcheSequenceLeftSide();
	}	
	else if( mouvement.move == E_MOVE_RIGHT_SIDE )
	{
		CtrlMarcheSequenceRightSide();
	}		
}

static void CtrlMarcheSequenceLeftSide( void ) 
{
	
}

static void CtrlMarcheSequenceRightSide( void ) 
{
	
}

static void CtrlMarcheSequenceLeft( void ) 
{
	
}

static void CtrlMarcheSequenceRight( void ) 
{
	
}

static void CtrlMarcheSequenceStop( void )
{
	CtrlPatteMove(AVANT_GAUCHE,		NEUTRE_EPAULE_AVANT_GAUCHE   ,	NEUTRE_COUDE_AVANT_GAUCHE   );		
	CtrlPatteMove(AVANT_DROITE,		NEUTRE_EPAULE_AVANT_DROITE   ,	NEUTRE_COUDE_AVANT_DROITE   );	
	CtrlPatteMove(MILIEU_GAUCHE,	NEUTRE_EPAULE_MILIEU_GAUCHE  ,	NEUTRE_COUDE_MILIEU_GAUCHE  );	
	CtrlPatteMove(MILIEU_DROITE,	NEUTRE_EPAULE_MILIEU_DROITE  ,	NEUTRE_COUDE_MILIEU_DROITE  );  
	CtrlPatteMove(ARRIERE_GAUCHE,	NEUTRE_EPAULE_ARRIERE_GAUCHE ,	NEUTRE_COUDE_ARRIERE_GAUCHE );
	CtrlPatteMove(ARRIERE_DROITE,	NEUTRE_EPAULE_ARRIERE_DROITE ,	NEUTRE_COUDE_ARRIERE_DROITE );
}	

static void CtrlMarcheSequenceBackward( void ) 
{
	if(step == 0)
	{	
		CtrlPatteMove(AVANT_DROITE,		NEUTRE_EPAULE_AVANT_DROITE	 + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE);	
		CtrlPatteMove(MILIEU_DROITE,	NEUTRE_EPAULE_MILIEU_DROITE  - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_MILIEU_DROITE );  
		CtrlPatteMove(ARRIERE_DROITE,	NEUTRE_EPAULE_AVANT_DROITE	 + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE);
		CtrlPatteMove(AVANT_GAUCHE,		NEUTRE_EPAULE_AVANT_GAUCHE	 + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_GAUCHE  );	
		CtrlPatteMove(MILIEU_GAUCHE,	NEUTRE_EPAULE_MILIEU_GAUCHE	 - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_MILIEU_GAUCHE + AMPLITUDE_MAX_COUDE);	
		CtrlPatteMove(ARRIERE_GAUCHE,	NEUTRE_EPAULE_ARRIERE_GAUCHE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_ARRIERE_GAUCHE );
		step = 1;
	}	
	else if(step == 1)
	{	
		CtrlPatteMove(AVANT_DROITE,		NEUTRE_EPAULE_AVANT_DROITE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE );
		CtrlPatteMove(MILIEU_DROITE,	NEUTRE_EPAULE_AVANT_DROITE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE);	
		CtrlPatteMove(ARRIERE_DROITE,	NEUTRE_EPAULE_AVANT_DROITE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE );
		CtrlPatteMove(AVANT_GAUCHE,		NEUTRE_EPAULE_AVANT_GAUCHE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_GAUCHE + AMPLITUDE_MAX_COUDE);	
		CtrlPatteMove(MILIEU_GAUCHE,	NEUTRE_EPAULE_MILIEU_GAUCHE - AMPLITUDE_MAX_EPAULE,	NEUTRE_COUDE_MILIEU_GAUCHE );	
		CtrlPatteMove(ARRIERE_GAUCHE,	NEUTRE_EPAULE_ARRIERE_GAUCHE + AMPLITUDE_MAX_EPAULE,NEUTRE_COUDE_ARRIERE_GAUCHE + AMPLITUDE_MAX_COUDE );
		step = 2;
	}	
	else if(step == 2)
	{	
		CtrlPatteMove(AVANT_DROITE,		NEUTRE_EPAULE_AVANT_DROITE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE  );
		CtrlPatteMove(MILIEU_DROITE,	NEUTRE_EPAULE_AVANT_DROITE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE);		
		CtrlPatteMove(ARRIERE_DROITE,	NEUTRE_EPAULE_AVANT_DROITE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE  );
		CtrlPatteMove(AVANT_GAUCHE,		NEUTRE_EPAULE_AVANT_GAUCHE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_GAUCHE + AMPLITUDE_MAX_COUDE);	
		CtrlPatteMove(MILIEU_GAUCHE,	NEUTRE_EPAULE_MILIEU_GAUCHE + AMPLITUDE_MAX_EPAULE,	NEUTRE_COUDE_MILIEU_GAUCHE );	
		CtrlPatteMove(ARRIERE_GAUCHE,	NEUTRE_EPAULE_ARRIERE_GAUCHE - AMPLITUDE_MAX_EPAULE,NEUTRE_COUDE_ARRIERE_GAUCHE + AMPLITUDE_MAX_COUDE);
		step = 3;
	}	
	else if(step == 3)
	{	
		CtrlPatteMove(AVANT_DROITE,		NEUTRE_EPAULE_AVANT_DROITE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE);
		CtrlPatteMove(MILIEU_DROITE,	NEUTRE_EPAULE_AVANT_DROITE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE );
		CtrlPatteMove(ARRIERE_DROITE,	NEUTRE_EPAULE_AVANT_DROITE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE);		
		CtrlPatteMove(AVANT_GAUCHE,		NEUTRE_EPAULE_AVANT_GAUCHE - AMPLITUDE_MAX_EPAULE,	NEUTRE_COUDE_AVANT_GAUCHE );		
		CtrlPatteMove(MILIEU_GAUCHE,	NEUTRE_EPAULE_MILIEU_GAUCHE + AMPLITUDE_MAX_EPAULE  ,	NEUTRE_COUDE_MILIEU_GAUCHE + AMPLITUDE_MAX_COUDE);	 
		CtrlPatteMove(ARRIERE_GAUCHE,	NEUTRE_EPAULE_ARRIERE_GAUCHE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_ARRIERE_GAUCHE);
		step = 0;
	}
}

static void CtrlMarcheSequenceForward( void )
{
	if(step == 0)
	{	
		CtrlPatteMove(AVANT_DROITE,		NEUTRE_EPAULE_AVANT_DROITE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE );	
		CtrlPatteMove(MILIEU_DROITE,	NEUTRE_EPAULE_MILIEU_DROITE - AMPLITUDE_MAX_EPAULE,	NEUTRE_COUDE_MILIEU_DROITE - AMPLITUDE_MAX_COUDE);  
		CtrlPatteMove(ARRIERE_DROITE,	NEUTRE_EPAULE_AVANT_DROITE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE );
		CtrlPatteMove(AVANT_GAUCHE,		NEUTRE_EPAULE_AVANT_GAUCHE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_GAUCHE + AMPLITUDE_MAX_COUDE );	
		CtrlPatteMove(MILIEU_GAUCHE,	NEUTRE_EPAULE_MILIEU_GAUCHE - AMPLITUDE_MAX_EPAULE,	NEUTRE_COUDE_MILIEU_GAUCHE );	
		CtrlPatteMove(ARRIERE_GAUCHE,	NEUTRE_EPAULE_ARRIERE_GAUCHE + AMPLITUDE_MAX_EPAULE,NEUTRE_COUDE_ARRIERE_GAUCHE + AMPLITUDE_MAX_COUDE );
		step = 1;
	}	
	else if(step == 1)
	{	
		CtrlPatteMove(AVANT_DROITE,		NEUTRE_EPAULE_AVANT_DROITE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE);
		CtrlPatteMove(MILIEU_DROITE,	NEUTRE_EPAULE_AVANT_DROITE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE );	
		CtrlPatteMove(ARRIERE_DROITE,	NEUTRE_EPAULE_AVANT_DROITE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE);
		CtrlPatteMove(AVANT_GAUCHE,		NEUTRE_EPAULE_AVANT_GAUCHE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_GAUCHE );	
		CtrlPatteMove(MILIEU_GAUCHE,	NEUTRE_EPAULE_MILIEU_GAUCHE - AMPLITUDE_MAX_EPAULE,	NEUTRE_COUDE_MILIEU_GAUCHE + AMPLITUDE_MAX_COUDE );	
		CtrlPatteMove(ARRIERE_GAUCHE,	NEUTRE_EPAULE_ARRIERE_GAUCHE + AMPLITUDE_MAX_EPAULE,NEUTRE_COUDE_ARRIERE_GAUCHE );
		step = 2;
	}	
	else if(step == 2)
	{	
		CtrlPatteMove(AVANT_DROITE,		NEUTRE_EPAULE_AVANT_DROITE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE );
		CtrlPatteMove(MILIEU_DROITE,	NEUTRE_EPAULE_AVANT_DROITE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE );		
		CtrlPatteMove(ARRIERE_DROITE,	NEUTRE_EPAULE_AVANT_DROITE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE );
		CtrlPatteMove(AVANT_GAUCHE,		NEUTRE_EPAULE_AVANT_GAUCHE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_GAUCHE );	
		CtrlPatteMove(MILIEU_GAUCHE,	NEUTRE_EPAULE_MILIEU_GAUCHE + AMPLITUDE_MAX_EPAULE,	NEUTRE_COUDE_MILIEU_GAUCHE + AMPLITUDE_MAX_COUDE );	
		CtrlPatteMove(ARRIERE_GAUCHE,	NEUTRE_EPAULE_ARRIERE_GAUCHE - AMPLITUDE_MAX_EPAULE,NEUTRE_COUDE_ARRIERE_GAUCHE );
		step = 3;
	}	
	else if(step == 3)
	{	
		CtrlPatteMove(AVANT_DROITE,		NEUTRE_EPAULE_AVANT_DROITE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE );
		CtrlPatteMove(MILIEU_DROITE,	NEUTRE_EPAULE_AVANT_DROITE + AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE - AMPLITUDE_MAX_COUDE);
		CtrlPatteMove(ARRIERE_DROITE,	NEUTRE_EPAULE_AVANT_DROITE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_AVANT_DROITE );		
		CtrlPatteMove(AVANT_GAUCHE,		NEUTRE_EPAULE_AVANT_GAUCHE - AMPLITUDE_MAX_EPAULE,	NEUTRE_COUDE_AVANT_GAUCHE + AMPLITUDE_MAX_COUDE  );		
		CtrlPatteMove(MILIEU_GAUCHE,	NEUTRE_EPAULE_MILIEU_GAUCHE + AMPLITUDE_MAX_EPAULE  ,	NEUTRE_COUDE_MILIEU_GAUCHE );	 
		CtrlPatteMove(ARRIERE_GAUCHE,	NEUTRE_EPAULE_ARRIERE_GAUCHE - AMPLITUDE_MAX_EPAULE ,	NEUTRE_COUDE_ARRIERE_GAUCHE + AMPLITUDE_MAX_COUDE);
		step = 0;
	}
}	